// ---------------------------------------------------------------------------
// ★ A CAP THAT CLOSES A TUBE MUST FACE OUT OF IT.
//
// glTF materials are single-sided. A triangle fan wound the wrong way is not
// drawn dark and is not drawn inside-out — it is NOT DRAWN, and what you see
// through the gap is whatever is behind it. That reads as a hole, and a hole in
// a character is rubric 3.7, which is binary.
//
// This gate exists because that mistake survived three independent reviews
// arguing about a picture.
//
// Tank's hand cap was wound inward on both arms and all three LODs: every one
// of the 14 fan triangles at the +x apex had a geometric normal of (-1, 0, 0),
// with the authored NORMAL attribute agreeing. The cause is ordinary — the
// predicate was the SHOULDER cap's, copied. The two caps close opposite ends of
// the same tube, so they cannot share a winding rule: on the right arm the
// shoulder cap faces -x and the hand cap faces +x. One `if side > 0` serves one
// of them and betrays the other.
//
// ⚠️ WHAT MAKES IT WORTH A GATE IS HOW BADLY IT WAS DIAGNOSED. The defect was
// first reported as an "open interior" seen down the arm's axis. It was then
// REFUTED by sampling ALPHA over the shoulder — 0 pixels below alpha 250,
// minimum 255 — and written up as a shadowed concavity, which is wrong. Alpha
// can only detect a hole in the OUTER silhouette. The torso sits behind the arm
// at every one of those pixels, so an interior hole is invisible to that test by
// construction: the reviewer who reproduced those exact numbers and then showed
// they proved nothing was right.
//
// A picture cannot settle this and geometry can, so this asks the geometry.
//
// The rule: at each extremity of a limb-like primitive, find the vertex that is
// furthest along an axis, take every triangle in its fan, and require the
// geometric normal to point AWAY from the mesh centroid. A fan around an apex
// is unambiguous — it is the end of a solid, and the outward direction is the
// direction the apex itself sticks out in.
//
// Break-it record, in the tests below: reversing one fan's winding fires with
// "kid_tank ... 14 of 14 apex-fan triangles face inward".
// ---------------------------------------------------------------------------

import { readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { readAccessor, readGlb } from './glb.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const models = resolve(here, '..', '..', 'public', 'v2', 'models');

// Only authored characters carry hand-written caps. The procedural roster
// baseline is generated by one code path that cannot get this wrong per-kid.
const AUTHORED = ['kid_tank.glb', 'kid_nostrike.glb'];

const cross = (u, v) => [
  u[1] * v[2] - u[2] * v[1],
  u[2] * v[0] - u[0] * v[2],
  u[0] * v[1] - u[1] * v[0],
];

/**
 * Every apex fan in a primitive, and how many of its triangles face inward.
 *
 * An "apex" is the extreme vertex along +x or -x. Those are the limb ends —
 * the hands, and on some characters the feet — and they are where a fan closes
 * a tube. A fan is only judged when it has at least three triangles, so an
 * ordinary corner vertex shared by two quads is never mistaken for a cap.
 */
function apexFans(gltf, prim, flip) {
  const position = readAccessor(gltf, prim.attributes.POSITION);
  const indices = readAccessor(gltf, prim.indices);
  const at = (i) => [position[i * 3], position[i * 3 + 1], position[i * 3 + 2]];

  let apex = -1;
  let best = -Infinity;
  // eslint-disable-next-line no-unused-vars
  for (let i = 0; i < position.length / 3; i++) {
    const value = flip * at(i)[0];
    if (value > best) { best = value; apex = i; }
  }

  const fan = [];
  const neighbours = new Set();
  for (let t = 0; t < indices.length; t += 3) {
    const tri = [indices[t], indices[t + 1], indices[t + 2]];
    if (!tri.includes(apex)) continue;
    fan.push(tri);
    for (const v of tri) if (v !== apex) neighbours.add(v);
  }
  if (fan.length < 3) return null;

  // ★ TWO CONDITIONS SEPARATE A CAP FROM AN ORDINARY VERTEX, and without them
  // this lint accuses the one approved character on the roster.
  //
  // A CLOSED fan has exactly as many neighbours as triangles — walk the ring
  // and you return to the start. An open patch edge has one more neighbour than
  // triangle, because the walk stops at both ends. And a cap's apex STICKS OUT:
  // every neighbour is strictly behind it along the axis.
  //
  // Junebug's extreme-x vertex failed both. It had 4 neighbours to 3 triangles
  // (an open edge on a grid patch) and two of them sat at exactly its own x, so
  // it protrudes by nothing. Its surface normal points along -z, which makes the
  // SIGN of its normal's x component meaningless noise — and the first cut of
  // this lint read that noise as a hole in an approved asset. Tank's real hand
  // cap has 14 neighbours to 14 triangles and stands 0.036ft proud of its ring.
  if (neighbours.size !== fan.length) return null;
  const apexAxis = flip * at(apex)[0];
  for (const n of neighbours) {
    if (apexAxis - flip * at(n)[0] < 0.01) return null;
  }

  let inward = 0;
  for (const [a, b, c] of fan) {
    const [A, B, C] = [at(a), at(b), at(c)];
    const n = cross(
      [B[0] - A[0], B[1] - A[1], B[2] - A[2]],
      [C[0] - A[0], C[1] - A[1], C[2] - A[2]],
    );
    // The apex sticks out along `flip * x`, so an outward cap's normal must too.
    if (flip * n[0] < 0) inward++;
  }
  return { apexX: at(apex)[0], total: fan.length, inward };
}

function windingErrors(reverse = null) {
  const errors = [];
  for (const file of AUTHORED) {
    if (!readdirSync(models).includes(file)) continue;
    const gltf = readGlb(join(models, file));
    for (const mesh of gltf.json.meshes ?? []) {
      mesh.primitives.forEach((prim, index) => {
        if (prim.indices === undefined || !prim.attributes?.POSITION) return;
        for (const flip of [1, -1]) {
          const fan = apexFans(gltf, prim, flip);
          if (!fan) continue;
          // The break-it hook: pretend one named fan was authored backwards.
          // ⚠️ Matched on a PREFIX. Blender's exporter appends `.001` to a mesh
          // name or does not, depending on what else is in the scene, and
          // pinning the full name made this hook silently match nothing — which
          // looks exactly like a passing test.
          const inward = reverse && reverse.file === file && mesh.name.startsWith(reverse.mesh)
            && reverse.prim === index && reverse.flip === flip
            ? fan.total - fan.inward
            : fan.inward;
          // ★ A CAP IS UNANIMOUS, AND THAT IS WHAT MAKES IT A CAP. Every
          // triangle in a fan that closes a tube faces the same way; a fan with
          // a MIXED verdict is an ordinary vertex on a curved surface that
          // happens to be the extreme one in its primitive, and judging it
          // produces false alarms. The first cut of this lint flagged Junebug
          // at "2 of 5" on a vertex at x=0.160 — nowhere near a limb end — on
          // an APPROVED character. Tank's real defect was 14 of 14.
          if (inward > 0 && inward === fan.total) {
            errors.push(
              `${file} ${mesh.name} prim${index}: ${inward} of ${fan.total} ` +
              `apex-fan triangles face inward at x=${fan.apexX.toFixed(3)} — ` +
              'reverse that fan\'s vertex order; a single-sided cap wound inward ' +
              'is not drawn at all and reads as a hole (rubric 3.7)',
            );
          }
        }
      });
    }
  }
  return errors;
}

describe('a cap that closes a tube faces out of it', () => {
  it('has no apex fan wound into the mesh', () => {
    expect(windingErrors()).toEqual([]);
  });

  // ★ Broken once, against the real geometry rather than a fixture: flipping
  // the hand fan reproduces exactly the defect that shipped.
  it('fires when a limb-end fan is wound inward', () => {
    const errors = windingErrors({
      file: 'kid_tank.glb', mesh: 'kid_tank_LOD0_Mesh', prim: 1, flip: 1,
    });
    expect(errors.some((error) => /apex-fan triangles face inward/.test(error))).toBe(true);
  });
});
